version: "3.8"
services:
  linktrim_app:
    build: 
      context: ./src
      dockerfile: LinkTrim.Web/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REDIS_CONNECTION=redis:6379  
    depends_on:
      - redis
  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - "6379:6379"
