services:
  linktrim_app:
    build: 
      context: ./src
      dockerfile: LinkTrim.Web/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - Options__HOST=http://localhost:5000
      - REDIS_CONNECTION=redis:6379  
    depends_on:
      - redis
  redis:
    image: "redis:7.2.4-alpine"
    command: [ "redis-server", "--appendonly", "no" ]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  redis-data:
